### ISSUE TITLE
申请开放捐赠 - Apply for an open donation

### ISSUE THREAD

**Issue by xuguangyuansh** [LightFocus/ASUS-ROG-STRIX-Z490G-Hackintosh#1]
#### 然后，希望获得持续更新
---

**Comment by LightFocus** [comment]
这个项目会根据每个月acidanthera那边的更新情况更新（一般为每个月第一个星期一），除非遇到下列情况之一：

1. macOS停止支持X86的机器
2. OpenCore官方(acidanthera)不再维护
3. 我本人不再使用黑苹果，或者是更换硬件

如果您觉得这个项目对您有帮助想捐赠的话，下面是二维码
![IMG_6818](https://user-images.githubusercontent.com/22290740/176673645-de5768fe-0265-47e9-b908-73ad86753d70.JPG)
谢谢您的支持
